
- name: assert all vars are set
  assert: 
    that:
      - item is defined
      - item | length > 0
    quiet: true
  loop:
  - installation_folder
  - temp_folder
  - reboot_after_install

- name: uninstall nvserver
  command: "{{ installation_folder }}/uninstall -q"
  become: yes
  ignore_errors: yes

- name: remove installation folder
  file:
    path: "{{ installation_folder }}"
    state: absent
  become: yes

# reboot the instance after uninstall (optional)

- name: reboot nvserver instance
  reboot:
    reboot_timeout: "{{ reboot_timeout | default(600) }}"
  become: yes
  when: reboot_after_install == True
