
# validation

- name: assert all vars are set
  assert: 
    that:
      - item is defined
      - item | length > 0
    quiet: true
  loop:
  - uplink_eth
  - wifi_eth
  - temp_folder
  - clear_temp_folder
  - installation_folder
  - clear_before_install
  - server_port
  - proxy_port
  - tunneling_port
  - app_version
  - nv_app_version
  - installer_file_name
  - ansible_user_id
  - s3_download_url
  - reboot_after_install
  - extra_java_options

- name: assert when mitm_use_certificate is true
  assert:
    that:
      - mitm_certificate_path != ''
    fail_msg: "'mitm_certificate_path' is not defined"
  when: mitm_use_certificate|bool == true

- name: make sure temp folder
  file:
    path: "{{ temp_folder }}"
    state: directory
    owner: "{{ ansible_user_id }}"
  become: yes

# download the file

- name: download zip from s3 url
  get_url:
    url: "{{ s3_download_url }}"
    dest: "{{ temp_folder }}/{{ installer_file_name }}"
    timeout: "{{ download_timeout | default(60) }}"
  when: custom_download_url == ""

- name: download zip from custom url
  get_url:
    url: "{{ custom_download_url }}"
    dest: "{{ temp_folder }}/{{ installer_file_name }}"
    timeout: "{{ download_timeout | default(60) }}"
  when: custom_download_url != ""
